# Generated by Django 3.2.10 on 2021-12-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField(default=1)),
                ('cost', models.PositiveIntegerField(default=1)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=150, unique=True)),
            ],
        ),
    ]
