# Generated by Django 3.2.10 on 2021-12-19 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Widget',
            new_name='Post',
        ),
    ]
